# 参考 https://tzuhui.io/2020/12/11/Vue/Vue-deploy-github-actions/

# This is a basic workflow to help you get started with Actions
name: Test Stage Branch

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - dev
      - feat/*
      - fix/*
      - perf/*
      - refactor/*
      - build/*
      - build/github-ci
  pull_request:
    branches:
      - dev
      - feat/*
      - fix/*
      - perf/*
      - refactor/*
      - build/*
      - build/github-ci

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Install & Build # 執行指令
        run: |
          yarn ci:test-stage-branch
